/** Dial codes for country selector (E.164 prefix without national number). Sorted by label. */
export type PhoneCountryOption = { iso: string; dial: string; label: string }

export const DEFAULT_PHONE_DIAL = '+1'

export const PHONE_COUNTRY_OPTIONS: PhoneCountryOption[] = [
  { iso: 'AF', dial: '+93', label: 'Afghanistan (+93)' },
  { iso: 'DZ', dial: '+213', label: 'Algeria (+213)' },
  { iso: 'AR', dial: '+54', label: 'Argentina (+54)' },
  { iso: 'AU', dial: '+61', label: 'Australia (+61)' },
  { iso: 'AT', dial: '+43', label: 'Austria (+43)' },
  { iso: 'BH', dial: '+973', label: 'Bahrain (+973)' },
  { iso: 'BD', dial: '+880', label: 'Bangladesh (+880)' },
  { iso: 'BE', dial: '+32', label: 'Belgium (+32)' },
  { iso: 'BR', dial: '+55', label: 'Brazil (+55)' },
  { iso: 'BG', dial: '+359', label: 'Bulgaria (+359)' },
  { iso: 'CA', dial: '+1', label: 'Canada (+1)' },
  { iso: 'CL', dial: '+56', label: 'Chile (+56)' },
  { iso: 'CN', dial: '+86', label: 'China (+86)' },
  { iso: 'CO', dial: '+57', label: 'Colombia (+57)' },
  { iso: 'CR', dial: '+506', label: 'Costa Rica (+506)' },
  { iso: 'HR', dial: '+385', label: 'Croatia (+385)' },
  { iso: 'CY', dial: '+357', label: 'Cyprus (+357)' },
  { iso: 'CZ', dial: '+420', label: 'Czech Republic (+420)' },
  { iso: 'DK', dial: '+45', label: 'Denmark (+45)' },
  { iso: 'EG', dial: '+20', label: 'Egypt (+20)' },
  { iso: 'FI', dial: '+358', label: 'Finland (+358)' },
  { iso: 'FR', dial: '+33', label: 'France (+33)' },
  { iso: 'DE', dial: '+49', label: 'Germany (+49)' },
  { iso: 'GH', dial: '+233', label: 'Ghana (+233)' },
  { iso: 'GR', dial: '+30', label: 'Greece (+30)' },
  { iso: 'HK', dial: '+852', label: 'Hong Kong (+852)' },
  { iso: 'HU', dial: '+36', label: 'Hungary (+36)' },
  { iso: 'IS', dial: '+354', label: 'Iceland (+354)' },
  { iso: 'IN', dial: '+91', label: 'India (+91)' },
  { iso: 'ID', dial: '+62', label: 'Indonesia (+62)' },
  { iso: 'IQ', dial: '+964', label: 'Iraq (+964)' },
  { iso: 'IE', dial: '+353', label: 'Ireland (+353)' },
  { iso: 'IL', dial: '+972', label: 'Israel (+972)' },
  { iso: 'IT', dial: '+39', label: 'Italy (+39)' },
  { iso: 'JP', dial: '+81', label: 'Japan (+81)' },
  { iso: 'JO', dial: '+962', label: 'Jordan (+962)' },
  { iso: 'KE', dial: '+254', label: 'Kenya (+254)' },
  { iso: 'KW', dial: '+965', label: 'Kuwait (+965)' },
  { iso: 'LB', dial: '+961', label: 'Lebanon (+961)' },
  { iso: 'MY', dial: '+60', label: 'Malaysia (+60)' },
  { iso: 'MX', dial: '+52', label: 'Mexico (+52)' },
  { iso: 'MA', dial: '+212', label: 'Morocco (+212)' },
  { iso: 'NL', dial: '+31', label: 'Netherlands (+31)' },
  { iso: 'NZ', dial: '+64', label: 'New Zealand (+64)' },
  { iso: 'NG', dial: '+234', label: 'Nigeria (+234)' },
  { iso: 'NO', dial: '+47', label: 'Norway (+47)' },
  { iso: 'OM', dial: '+968', label: 'Oman (+968)' },
  { iso: 'PK', dial: '+92', label: 'Pakistan (+92)' },
  { iso: 'PS', dial: '+970', label: 'Palestine (+970)' },
  { iso: 'PE', dial: '+51', label: 'Peru (+51)' },
  { iso: 'PH', dial: '+63', label: 'Philippines (+63)' },
  { iso: 'PL', dial: '+48', label: 'Poland (+48)' },
  { iso: 'PT', dial: '+351', label: 'Portugal (+351)' },
  { iso: 'QA', dial: '+974', label: 'Qatar (+974)' },
  { iso: 'RO', dial: '+40', label: 'Romania (+40)' },
  { iso: 'RU', dial: '+7', label: 'Russia (+7)' },
  { iso: 'SA', dial: '+966', label: 'Saudi Arabia (+966)' },
  { iso: 'RS', dial: '+381', label: 'Serbia (+381)' },
  { iso: 'SG', dial: '+65', label: 'Singapore (+65)' },
  { iso: 'SK', dial: '+421', label: 'Slovakia (+421)' },
  { iso: 'ZA', dial: '+27', label: 'South Africa (+27)' },
  { iso: 'KR', dial: '+82', label: 'South Korea (+82)' },
  { iso: 'ES', dial: '+34', label: 'Spain (+34)' },
  { iso: 'SE', dial: '+46', label: 'Sweden (+46)' },
  { iso: 'CH', dial: '+41', label: 'Switzerland (+41)' },
  { iso: 'TW', dial: '+886', label: 'Taiwan (+886)' },
  { iso: 'TZ', dial: '+255', label: 'Tanzania (+255)' },
  { iso: 'TH', dial: '+66', label: 'Thailand (+66)' },
  { iso: 'TN', dial: '+216', label: 'Tunisia (+216)' },
  { iso: 'TR', dial: '+90', label: 'Turkey (+90)' },
  { iso: 'UA', dial: '+380', label: 'Ukraine (+380)' },
  { iso: 'AE', dial: '+971', label: 'United Arab Emirates (+971)' },
  { iso: 'GB', dial: '+44', label: 'United Kingdom (+44)' },
  { iso: 'US', dial: '+1', label: 'United States (+1)' },
  { iso: 'VN', dial: '+84', label: 'Vietnam (+84)' },
]
